# Travis configuration file for slycot
language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - TEST_CONDA=0
  - TEST_CONDA=1

before_install:
  #
  # If not using conda, then install gfortran.  Also need to include
  # liblapack here and set up library paths
  #
  - if [[ $TEST_CONDA == 0 ]]; then
      sudo apt-get install gfortran liblapack-dev;
    fi

install:
  #
  # Install miniconda to allow quicker installation of dependencies
  # See https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
  #
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - if [[ $TEST_CONDA == 1 ]]; then conda install conda-build; fi
  - conda info -a
  #
  # coveralls not in conda repos :-(
  - pip install coveralls
  #
  # Set up a test environment for testing everything out
  - conda create -q -n test-environment python="$TRAVIS_PYTHON_VERSION" pip coverage nose numpy
  - source activate test-environment
  #
  # Install the slycot package (two ways, to improve robustness)
  - if [[ $TEST_CONDA == 1 ]]; then
      conda build conda-recipe;
      conda install slycot --use-local;
    else
      export LIBRARY_PATH="$HOME/miniconda/envs/test-environment/lib";
      python setup.py install;
    fi

script:
  # Local unit tests
  # TODO: replace with nose?
  - python runtests.py --coverage
  #
  # As a deeper set of tests, get test against python-control as well
  #
  # Additional packages required for python-control
  - conda install scipy matplotlib
  # Install display manager to allow testing of plotting functions
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Get python-control from source and install
  - git clone https://github.com/python-control/python-control.git control
  - cd control; python setup.py test

after_success:
  - coveralls
