package:
  name: slycot
  version: "0.3.0"

build:
  number: 1

  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install

requirements:
  build:
    - python
    - numpy
    - lapack

  run:
    - python
    - numpy
    - lapack

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
