package:
  name: slycot
  version: "0.3.2"

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - openblas
    - m2w64-gcc-fortran # [win]
    - gfortran_linux-64	# [linux]
    - gfortran_osx-64	# [osx]

  run:
    - python
    - numpy
    - openblas

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/Slycot
  license:  GPLv2
  summary: 'A wrapper for the SLICOT control and systems library'
